services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb-cancela
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cancela
      POSTGRES_PASSWORD: cancela123
      POSTGRES_DB: cancela_db
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana-cancela
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: 123123a
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/cancela-dashboard.json
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - timescaledb

volumes:
  timescale_data:
  grafana_data:
